# Generated by Django 5.0 on 2023-12-15 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='desciption',
            field=models.TextField(),
        ),
    ]
