# Generated by Django 5.0 on 2023-12-15 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_desciption_product_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='icon',
        ),
    ]
